In [4]:

import os, json, datetime
import numpy as np
import pandas as pd
import fastf1 as ff1

from pathlib import Path
import datetime

In [6]:
# check the paths work from this notebook?


#i just want to check paths, trauma from when the cache went all over the place, wrong folder, went to tmp fml

#DONT NEED THE CACHE DIR BROTHER
# CACHE_DIR = Path(CACHE_DIR)   # <-- this is the missing line

# test_file = CACHE_DIR / "_cache_path_test.txt"
# with open(test_file, "w") as f:
#     f.write(f"Cache test written at {datetime.datetime.now().isoformat()}\n")

# print("Test file written to:", test_file)



OUT_DIR   = "../../data_processed"

OUT_DIR = Path(OUT_DIR)   # <-- this is the missing line
testp_file = OUT_DIR / "_parquets_path_test.txt"
with open(testp_file, "w") as f:
    f.write(f"Parquets test written at {datetime.datetime.now().isoformat()}\n")
    f.write(f"Works from the ml notebook fool\n")


print("Test file written to:", testp_file)

Test file written to: ..\..\data_processed\_parquets_path_test.txt

In [8]:
from pathlib import Path
import pandas as pd


DATASET_PATH = OUT_DIR / "preq_dataset.parquet"

df = pd.read_parquet(DATASET_PATH)
print(df.shape)

(2976, 16)

In [9]:
df

,year,round,event_name,country,location,driver,n_fp_laps,n_fp_sessions_participated,best_fp_lap_time_overall,avg_fp_lap_time,median_fp_lap_time,best_last_fp_lap_time,best_last_fp_s1,best_last_fp_s2,best_last_fp_s3,quali_position
0,2018,1,Australian Grand Prix,Australia,Melbourne,ALO,43,3,85.200,98.581512,96.2460,94.298,31.144,25.268,37.886,11.0
1,2018,1,Australian Grand Prix,Australia,Melbourne,BOT,63,3,84.159,98.692540,94.1740,94.174,31.326,25.150,37.698,10.0
2,2018,1,Australian Grand Prix,Australia,Melbourne,ERI,61,3,86.814,100.017279,90.7760,88.890,29.842,23.687,35.361,17.0
3,2018,1,Australian Grand Prix,Australia,Melbourne,GAS,69,3,85.945,99.882739,91.8910,94.990,31.187,25.521,38.282,20.0
4,2018,1,Australian Grand Prix,Australia,Melbourne,GRO,54,3,84.648,96.055611,90.5690,96.171,31.767,25.553,38.851,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2971,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,SAI,36,2,83.871,100.196750,90.0295,83.871,17.199,36.013,30.507,3.0
2972,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,STR,38,2,84.531,106.555658,90.9135,84.531,17.324,36.170,30.886,13.0
2973,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,TSU,38,2,84.343,111.313000,103.8435,84.343,17.303,36.247,30.793,11.0
2974,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,VER,35,2,83.844,105.660657,95.0140,83.844,17.206,36.156,30.482,5.0
2975,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,ZHO,44,3,84.557,104.743114,91.0080,84.668,17.386,36.371,30.910,17.0

In [10]:
df = df[df["quali_position"].notna()].reset_index(drop=True)

In [11]:
df

,year,round,event_name,country,location,driver,n_fp_laps,n_fp_sessions_participated,best_fp_lap_time_overall,avg_fp_lap_time,median_fp_lap_time,best_last_fp_lap_time,best_last_fp_s1,best_last_fp_s2,best_last_fp_s3,quali_position
0,2018,1,Australian Grand Prix,Australia,Melbourne,ALO,43,3,85.200,98.581512,96.2460,94.298,31.144,25.268,37.886,11.0
1,2018,1,Australian Grand Prix,Australia,Melbourne,BOT,63,3,84.159,98.692540,94.1740,94.174,31.326,25.150,37.698,10.0
2,2018,1,Australian Grand Prix,Australia,Melbourne,ERI,61,3,86.814,100.017279,90.7760,88.890,29.842,23.687,35.361,17.0
3,2018,1,Australian Grand Prix,Australia,Melbourne,GAS,69,3,85.945,99.882739,91.8910,94.990,31.187,25.521,38.282,20.0
4,2018,1,Australian Grand Prix,Australia,Melbourne,GRO,54,3,84.648,96.055611,90.5690,96.171,31.767,25.553,38.851,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,SAI,36,2,83.871,100.196750,90.0295,83.871,17.199,36.013,30.507,3.0
2969,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,STR,38,2,84.531,106.555658,90.9135,84.531,17.324,36.170,30.886,13.0
2970,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,TSU,38,2,84.343,111.313000,103.8435,84.343,17.303,36.247,30.793,11.0
2971,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,VER,35,2,83.844,105.660657,95.0140,83.844,17.206,36.156,30.482,5.0
2972,2024,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island,ZHO,44,3,84.557,104.743114,91.0080,84.668,17.386,36.371,30.910,17.0

In [12]:
TARGET = "quali_position"
DROP_COLS = ["year","round","event_name","country","location","driver"]

X = df.drop(columns=DROP_COLS + [TARGET])
y = df[TARGET]

In [13]:
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor

groups = df["year"]   # LOYO by year

gkf = GroupKFold(n_splits=len(groups.unique()))

maes = []

for train_idx, test_idx in gkf.split(X, y, groups):
    Xtr, Xte = X.iloc[train_idx], X.iloc[test_idx]
    ytr, yte = y.iloc[train_idx], y.iloc[test_idx]

    model = XGBRegressor(
        n_estimators=200,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        objective="reg:squarederror"
    )

    model.fit(Xtr, ytr)
    preds = model.predict(Xte)
    maes.append(mean_absolute_error(yte, preds))

print("Baseline LOYO MAE:", sum(maes)/len(maes))

Baseline LOYO MAE: 4.795286672026031

In [14]:
import optuna

def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "max_depth": trial.suggest_int("max_depth", 2, 6),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "objective": "reg:squarederror",
        "random_state": 42,
    }

    maes = []

    for tr, te in gkf.split(X, y, groups):
        model = XGBRegressor(**params)
        model.fit(X.iloc[tr], y.iloc[tr])
        preds = model.predict(X.iloc[te])
        maes.append(mean_absolute_error(y.iloc[te], preds))

    return sum(maes) / len(maes)

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=40)

print("Best MAE:", study.best_value)
print("Best params:", study.best_params)

c:\Users\aadha\anaconda3\envs\f1ml\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-03-01 11:31:31,666] A new study created in memory with name: no-name-a270fd9e-50b5-4d1f-9013-9993c8f0629a
[I 2026-03-01 11:31:33,461] Trial 0 finished with value: 5.035596213386298 and parameters: {'n_estimators': 727, 'max_depth': 3, 'learning_rate': 0.14016148827501465, 'subsample': 0.6113694427111653, 'colsample_bytree': 0.6640808580252927}. Best is trial 0 with value: 5.035596213386298.
[I 2026-03-01 11:31:34,283] Trial 1 finished with value: 4.893874385086852 and parameters: {'n_estimators': 468, 'max_depth': 2, 'learning_rate': 0.09036724498528163, 'subsample': 0.7379936185033411, 'colsample_bytree': 0.6186257020450407}. Best is trial 1 with value: 4.893874385086852.
[I 2026-03-01 11:31:36,427] Trial 2 finished with value: 4.744464789783486 and parameters: {'n_estimators': 602, 'max_depth': 5, 'learning_rate': 0.010980238707805939, 'subsample': 0.9388754599378991, 'colsample_bytree': 0.631280028344981}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:38,290] Trial 3 finished with value: 4.990839773377059 and parameters: {'n_estimators': 461, 'max_depth': 5, 'learning_rate': 0.11801159490238822, 'subsample': 0.9086331037555856, 'colsample_bytree': 0.7776473731838331}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:39,847] Trial 4 finished with value: 4.880515683533564 and parameters: {'n_estimators': 698, 'max_depth': 2, 'learning_rate': 0.012845205990038638, 'subsample': 0.778674588663595, 'colsample_bytree': 0.8177604120872093}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:41,928] Trial 5 finished with value: 4.757856272319686 and parameters: {'n_estimators': 525, 'max_depth': 5, 'learning_rate': 0.03381689595266159, 'subsample': 0.6858700547735691, 'colsample_bytree': 0.7231984503420065}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:43,635] Trial 6 finished with value: 4.748089552232912 and parameters: {'n_estimators': 364, 'max_depth': 5, 'learning_rate': 0.04083904916096273, 'subsample': 0.8426231890711668, 'colsample_bytree': 0.686766536311864}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:44,968] Trial 7 finished with value: 4.891895496951045 and parameters: {'n_estimators': 697, 'max_depth': 2, 'learning_rate': 0.08626327244840903, 'subsample': 0.7795427082713748, 'colsample_bytree': 0.7440914465899824}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:47,143] Trial 8 finished with value: 4.803269394841204 and parameters: {'n_estimators': 519, 'max_depth': 5, 'learning_rate': 0.03798548678548543, 'subsample': 0.7239623030568266, 'colsample_bytree': 0.9613908004008919}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:47,705] Trial 9 finished with value: 4.8825027566833 and parameters: {'n_estimators': 261, 'max_depth': 2, 'learning_rate': 0.1854935438458796, 'subsample': 0.7106776830140055, 'colsample_bytree': 0.8896338202223764}. Best is trial 2 with value: 4.744464789783486.
[I 2026-03-01 11:31:50,845] Trial 10 finished with value: 4.735077375319281 and parameters: {'n_estimators': 604, 'max_depth': 6, 'learning_rate': 0.010266723170059515, 'subsample': 0.9900717540865912, 'colsample_bytree': 0.6263293939547947}. Best is trial 10 with value: 4.735077375319281.
[I 2026-03-01 11:31:53,699] Trial 11 finished with value: 4.729315736245526 and parameters: {'n_estimators': 592, 'max_depth': 6, 'learning_rate': 0.010860958865777703, 'subsample': 0.9963984072056393, 'colsample_bytree': 0.6049791762420205}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:31:56,849] Trial 12 finished with value: 4.745681199782508 and parameters: {'n_estimators': 601, 'max_depth': 6, 'learning_rate': 0.018541201652838835, 'subsample': 0.9839090868388328, 'colsample_bytree': 0.6112836967244353}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:32:01,342] Trial 13 finished with value: 4.818625077001029 and parameters: {'n_estimators': 798, 'max_depth': 6, 'learning_rate': 0.02023790981319263, 'subsample': 0.999415133940192, 'colsample_bytree': 0.8287734486786723}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:32:04,436] Trial 14 finished with value: 4.7625980297268535 and parameters: {'n_estimators': 606, 'max_depth': 6, 'learning_rate': 0.02018774551062855, 'subsample': 0.8794863898585527, 'colsample_bytree': 0.6873945868298841}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:32:05,551] Trial 15 finished with value: 4.8110242512832375 and parameters: {'n_estimators': 321, 'max_depth': 4, 'learning_rate': 0.013873324309014572, 'subsample': 0.9408194827115168, 'colsample_bytree': 0.601987306348799}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:32:07,724] Trial 16 finished with value: 4.761160364644636 and parameters: {'n_estimators': 649, 'max_depth': 4, 'learning_rate': 0.025571067633786197, 'subsample': 0.8406485839883574, 'colsample_bytree': 0.6583874286445026}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:32:10,058] Trial 17 finished with value: 4.7334990822657 and parameters: {'n_estimators': 405, 'max_depth': 6, 'learning_rate': 0.010289091499864584, 'subsample': 0.9562394229193589, 'colsample_bytree': 0.872211412320817}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:32:11,252] Trial 18 finished with value: 4.820878161928502 and parameters: {'n_estimators': 393, 'max_depth': 3, 'learning_rate': 0.05956791037863621, 'subsample': 0.9423594267589581, 'colsample_bytree': 0.8805333419489352}. Best is trial 11 with value: 4.729315736245526.
[I 2026-03-01 11:32:13,824] Trial 19 finished with value: 4.705888009133067 and parameters: {'n_estimators': 417, 'max_depth': 6, 'learning_rate': 0.015578346862257491, 'subsample': 0.8836224017995821, 'colsample_bytree': 0.9212351764810511}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:14,659] Trial 20 finished with value: 4.828876945145226 and parameters: {'n_estimators': 203, 'max_depth': 4, 'learning_rate': 0.016325553333061137, 'subsample': 0.8791919931610639, 'colsample_bytree': 0.9943439088009142}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:17,368] Trial 21 finished with value: 4.745451052205254 and parameters: {'n_estimators': 389, 'max_depth': 6, 'learning_rate': 0.02874484645151641, 'subsample': 0.9081787399747795, 'colsample_bytree': 0.910106215384395}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:20,345] Trial 22 finished with value: 4.732194974133761 and parameters: {'n_estimators': 440, 'max_depth': 6, 'learning_rate': 0.013705976467713137, 'subsample': 0.9582936520847837, 'colsample_bytree': 0.9309120417039004}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:23,620] Trial 23 finished with value: 4.709191551246483 and parameters: {'n_estimators': 471, 'max_depth': 6, 'learning_rate': 0.014738404610874736, 'subsample': 0.8381273255474596, 'colsample_bytree': 0.9288966497509464}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:26,656] Trial 24 finished with value: 4.732757300904145 and parameters: {'n_estimators': 546, 'max_depth': 5, 'learning_rate': 0.024822006588960457, 'subsample': 0.8263417979103331, 'colsample_bytree': 0.8496137040747258}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:29,046] Trial 25 finished with value: 4.724994956349277 and parameters: {'n_estimators': 323, 'max_depth': 6, 'learning_rate': 0.015689646200317917, 'subsample': 0.802595606951159, 'colsample_bytree': 0.9449634652722116}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:30,840] Trial 26 finished with value: 4.812706346896585 and parameters: {'n_estimators': 311, 'max_depth': 5, 'learning_rate': 0.052681944548697894, 'subsample': 0.7990581470877854, 'colsample_bytree': 0.9517748195410354}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:33,302] Trial 27 finished with value: 4.709664786233597 and parameters: {'n_estimators': 314, 'max_depth': 6, 'learning_rate': 0.017368536499742487, 'subsample': 0.7552835961198313, 'colsample_bytree': 0.987883226097028}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:34,344] Trial 28 finished with value: 4.779923736149182 and parameters: {'n_estimators': 236, 'max_depth': 4, 'learning_rate': 0.021982670996307987, 'subsample': 0.6592795124652091, 'colsample_bytree': 0.998213657298123}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:35,870] Trial 29 finished with value: 4.770983553004764 and parameters: {'n_estimators': 434, 'max_depth': 3, 'learning_rate': 0.029850666858309893, 'subsample': 0.7583246249650673, 'colsample_bytree': 0.9728653937853785}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:38,079] Trial 30 finished with value: 4.734164465786391 and parameters: {'n_estimators': 278, 'max_depth': 6, 'learning_rate': 0.015181566050026235, 'subsample': 0.6250248657614733, 'colsample_bytree': 0.9180466984661799}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:40,716] Trial 31 finished with value: 4.7242924545439875 and parameters: {'n_estimators': 344, 'max_depth': 6, 'learning_rate': 0.017637124352955055, 'subsample': 0.821075841397925, 'colsample_bytree': 0.9435599348106547}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:43,427] Trial 32 finished with value: 4.729946079158736 and parameters: {'n_estimators': 342, 'max_depth': 6, 'learning_rate': 0.02250539267616077, 'subsample': 0.8678170620298067, 'colsample_bytree': 0.9734508044328464}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:46,244] Trial 33 finished with value: 4.7348596158030976 and parameters: {'n_estimators': 476, 'max_depth': 5, 'learning_rate': 0.01732083253169848, 'subsample': 0.8252768784637806, 'colsample_bytree': 0.9039246477040591}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:48,544] Trial 34 finished with value: 4.7436007974896865 and parameters: {'n_estimators': 288, 'max_depth': 6, 'learning_rate': 0.012588549458732855, 'subsample': 0.9117623349115047, 'colsample_bytree': 0.9286100139944888}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:50,640] Trial 35 finished with value: 4.723365247251038 and parameters: {'n_estimators': 356, 'max_depth': 5, 'learning_rate': 0.017605850037688126, 'subsample': 0.7609607187653608, 'colsample_bytree': 0.8510224659950271}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:53,303] Trial 36 finished with value: 4.735434118743788 and parameters: {'n_estimators': 425, 'max_depth': 5, 'learning_rate': 0.012840950198827236, 'subsample': 0.7490998286568239, 'colsample_bytree': 0.7879564132294661}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:55,420] Trial 37 finished with value: 4.747444808528364 and parameters: {'n_estimators': 370, 'max_depth': 5, 'learning_rate': 0.03149072443119163, 'subsample': 0.7742441455063394, 'colsample_bytree': 0.8560872241813349}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:32:58,306] Trial 38 finished with value: 4.856933906373686 and parameters: {'n_estimators': 469, 'max_depth': 5, 'learning_rate': 0.06876941445203656, 'subsample': 0.6872109991157918, 'colsample_bytree': 0.821530938109107}. Best is trial 19 with value: 4.705888009133067.
[I 2026-03-01 11:33:01,359] Trial 39 finished with value: 4.754523734781914 and parameters: {'n_estimators': 510, 'max_depth': 5, 'learning_rate': 0.026149333145018175, 'subsample': 0.8564807485776741, 'colsample_bytree': 0.8972435143952963}. Best is trial 19 with value: 4.705888009133067.

Best MAE: 4.705888009133067
Best params: {'n_estimators': 417, 'max_depth': 6, 'learning_rate': 0.015578346862257491, 'subsample': 0.8836224017995821, 'colsample_bytree': 0.9212351764810511}

In [15]:
from pathlib import Path
import pandas as pd

def find_repo_root(start: Path) -> Path:
    start = start.resolve()
    for p in [start] + list(start.parents):
        if (p / "data_processed").exists():
            return p
    raise FileNotFoundError("Could not find repo root (folder containing data_processed).")

REPO_ROOT = find_repo_root(Path.cwd())
DATASET_PATH = REPO_ROOT / "data_processed" / "preq_dataset.parquet"

df = pd.read_parquet(DATASET_PATH)
df = df[df["quali_position"].notna()].reset_index(drop=True)

print("Loaded:", df.shape)
print("Years:", sorted(df["year"].unique()))

Loaded: (2973, 16)
Years: [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [16]:
TARGET = "quali_position"
KEY_COLS = ["year","round","event_name","country","location","driver"]

X = df.drop(columns=KEY_COLS + [TARGET])
y = df[TARGET].astype(float)

In [17]:
import numpy as np
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor

def eval_loyo_mae(X, y, groups, params):
    gkf = GroupKFold(n_splits=len(np.unique(groups)))
    fold_mae = {}

    for tr, te in gkf.split(X, y, groups):
        yr = int(pd.Series(groups).iloc[te].unique()[0])

        model = XGBRegressor(**params)
        model.fit(X.iloc[tr], y.iloc[tr])
        pred = model.predict(X.iloc[te])

        mae = mean_absolute_error(y.iloc[te], pred)
        fold_mae[yr] = mae

    return fold_mae

In [18]:
best_params = {
    "n_estimators": 417,
    "max_depth": 6,
    "learning_rate": 0.015578346862257491,
    "subsample": 0.8836224017995821,
    "colsample_bytree": 0.9212351764810511,
    "objective": "reg:squarederror",
    "random_state": 42,
}

groups = df["year"].values

fold_mae = eval_loyo_mae(X, y, groups, best_params)
print("LOYO MAE by year:")
for yr in sorted(fold_mae):
    print(yr, "->", fold_mae[yr])

print("Mean LOYO MAE:", sum(fold_mae.values()) / len(fold_mae))

LOYO MAE by year:
2018 -> 4.1547307843253725
2019 -> 4.103654438799078
2020 -> 4.919810310577573
2021 -> 4.813022782427846
2022 -> 5.158684067292647
2023 -> 5.013870523400502
2024 -> 4.777443157108443
Mean LOYO MAE: 4.705888009133067

In [19]:
final_model = XGBRegressor(**best_params)
final_model.fit(X, y)

# feature importance (gain-based)
importances = pd.Series(final_model.feature_importances_, index=X.columns).sort_values(ascending=False)
print(importances.head(15))

best_last_fp_lap_time         0.139756
best_last_fp_s3               0.133125
best_last_fp_s2               0.130845
best_last_fp_s1               0.129456
best_fp_lap_time_overall      0.128264
n_fp_sessions_participated    0.102984
median_fp_lap_time            0.093400
avg_fp_lap_time               0.081460
n_fp_laps                     0.060710
dtype: float32